version: '3.7'

services:
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - zipkin-network

  postgres_users:
    image: postgres:15.3
    container_name: users_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=users_db
    volumes:
      - users_pgdata:/var/lib/postgresql/data
      - ./sql-scripts/created_user_db.sql:/docker-entrypoint-initdb.d/created_user_db.sql
    networks:
      - postgres-network
    restart: always

  postgres_quotes:
    image: postgres:15.3
    container_name: quotes_db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=quotes_db
    volumes:
      - quotes_pgdata:/var/lib/postgresql/data
      - ./sql-scripts/created_quote_db.sql:/docker-entrypoint-initdb.d/created_quote_db.sql
    networks:
      - postgres-network
    restart: always

  postgres_votes:
    image: postgres:15.3
    container_name: votes_db
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=votes_db
    volumes:
      - votes_pgdata:/var/lib/postgresql/data
      - ./sql-scripts/created_votes_db.sql:/docker-entrypoint-initdb.d/created_votes_db.sql
    networks:
      - postgres-network
    restart: always

  discovery-service:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

networks:
  zipkin-network:
    driver: bridge
  postgres-network:
    driver: bridge

volumes:
  users_pgdata:
  quotes_pgdata:
  votes_pgdata: