eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka

server:
  port: 8222

spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:instead

  cloud:
    gateway:
      routes:


management:
  tracing:
    sampling:
      probability: 1.0

zipkin:
  tracing:
    endpoint: http://zipkin:9411/api/v2/spans
