FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY build/libs/discovery-service-0.0.1-SNAPSHOT.jar /app/discovery-service-0.0.1-SNAPSHOT.jar
CMD ["java", "-jar", "discovery-service-0.0.1-SNAPSHOT.jar"]
