eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: user-service
  config:
    import: optional:configserver:instead
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/users_db
    username: admin
    password: root

  flyway:
    locations: classpath:db/migration


management:
  tracing:
    sampling:
      probability: 1.0

zipkin:
  tracing:
    endpoint: http://zipkin:9411/api/v2/spans
